config/routes.rb
Rails.application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'
  get 'errors/not_found'

  get 'errors/internal_server_error'

  root to: 'home#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks",
                                    :registrations => 'users/registrations' }
  begin
    ActiveAdmin.routes(self)
  rescue Exception => e
    puts "ActiveAdmin: #{e.class}: #{e}"
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  namespace :home, path: '/' do
    get :about
    get :become_guide
    get :partners
    get :term_of_services, path: 'term-of-services'
    get :privacy_policy, path: 'privacy-policy'
    get :copyright
    get :contact_us
    post :send_contact
    get :help
    get :example
    get :founders
    get :how_it_works, path: 'how-it-works'
    get :safety
    get :careers
    get :blog
  end

  resources :search, only: [:index, :create] do
  end

  resources :tours, path: 'tours' do
    member do
      get :profile
      put :update_profile, path: 'profile'
      patch :update_profile, path: 'profile'
      get :tour_itinerary
      put :update_tour_itinerary, path: 'tour_itinerary'
      get :additional_info
      put :update_additional_info, path: 'additional_info'
      get :preview
      put :update_preview, path: 'preview'
    end
    resources :reservations do
      member do
        get :passenger
        get :billing_information
        get :review_and_submit
      end
    end
  end

  resources :users, only: [:show, :update] do
    member do
      get :public_profile
    end
  end

  resources :users, only: [:index], path: '/manage/profile' do
    collection do
      get :host, path: 'guide'
      post 'become_guide' => 'hosts#create', :as => 'become_guide'
      get :references
      get :reservations
      get :travels
      get :crafted_tours
      get :verifications
      get :account_settings
      get :profile_information
      get :availability
      get :bank_accounts
      post :twilio_send_message
      post :twilio_verify
      resources :bank_accounts, only: [:create, :update]
    end
  end

  namespace :users, path: '/manage/profile' do
    devise_scope :user do
      resources :references, only: [] do
        collection do
          post :email
          post :facebook
          post :twitter
          post :google_plus
        end
      end
    end
  end

  resources :messages

  resources :countries do
    resources :cities, only: [:show]
  end

  resources :subscribers, only: [:create]
end

app/models/concerns/user/private.rb
module User::Private
  extend ActiveSupport::Concern
  include JsonField

  included do
    before_validation :add_slug_if_not_assigned, on: :create
    before_validation :update_json_field
    after_validation :generate_invite_code, on: :create
  end

  private

  def add_slug_if_not_assigned
    self.username = (first_name && last_name) ? "#{first_name}_#{last_name}".downcase : "#{self.email[/^[^@]+/]}_#{Devise.friendly_token}"
  end

  def generate_invite_code
    self.invite_code = SecureRandom.uuid
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  DEFAULT_NAME = "TourMega Lovers"
  DEFAULT_AVATAR_URL = Figaro.env.DEFAULT_AVATAR_URL
  GENDERS = ["Male", "Female"]
  GUIDE_TYPE = [  :licensed_tour_company,
                  :licensed_local_guide,
                  :unlicensed_local_guide
                ]

  devise :database_authenticatable, :registerable, :recoverable, :async, :confirmable,
         :rememberable, :trackable, :validatable, :lockable, :omniauthable, :omniauth_providers => [:facebook, :twitter, :linkedin]

  include Private
  # extend FriendlyId
  # friendly_id :username, use: :slugged

  has_many :verifications, dependent: :destroy
  has_one :host, dependent: :destroy
  has_many :tours
  has_many :active_tours, -> { where(visible: true) }, foreign_key: 'user_id', class_name: "Tour"
  belongs_to :primary_address, class_name: 'Location', foreign_key: :primary_address_id, dependent: :destroy
  belongs_to :nationality, class_name: 'Country', foreign_key: :nationality_id
  has_many :reservations, dependent: :destroy
  has_many :bank_accounts, dependent: :destroy

  enum guide_type: GUIDE_TYPE
  accepts_nested_attributes_for :host

  mount_uploader :avatar, AvatarUploader
  mount_uploader :video_presentation, VideoUploader

  # validates :slug, presence: true, uniqueness: true
  validates :first_name, :last_name, presence: true

  class << self
    def collection
      select(:first_name, :last_name, :id).map{ |user| [user.first_name.to_s + ' ' + user.last_name.to_s, user.id] }
    end

    def from_omniauth(auth, user = nil, only_verified = false)
      unless only_verified
        email =
          case auth.provider
          when 'facebook'
            auth.info.email
          when 'twitter'
            auth.info.nickname.concat('@twitter.com')
          when 'linkedin'
            auth.info.email
          end
        user = find_by(email: email) || where(provider: auth.provider, uid: auth.uid).first_or_initialize
        user.email = email
        user.provider = auth.provider
        user.uid = auth.uid
        user.phone_number = auth.info.phone
        user.first_name = auth.info.name.split(' ')[0..-2].join(' ')
        user.last_name = auth.info.name.split(' ').last
        user.password = Devise.friendly_token[0, 20]
        user.remote_avatar_url = auth.info.image
        user.skip_confirmation! unless user.confirmed?
        user.save
      end
      user.verify_by_omniauth(auth)
      user
    end

    def import_from_external(user_json, provider)
      where(provider: provider, uid: user_json['id'].to_s).first_or_create do |user|
        user.email = "#{user_json['username']}@tournative.com"
        user.username = "#{provider}-#{user_json['username']}"
        user.first_name = user_json['full_name'].split(' ')[0..-2].join(' ')
        user.last_name = user_json['full_name'].split(' ').last
        user.remote_avatar_url = user_json['avatar']
        user.password = Devise.friendly_token[0, 20]
      end
      user = User.find_by(email: "#{user_json['username']}@tournative.com")

      filepath = "db/csv/#{Date.today.to_formatted_s(:number)}_users.csv"
      CSV.open(filepath, 'a+') do |csv|
        row = [ user.email, user.username, user.first_name, user.last_name, user.remote_avatar_url, user.provider, user.uid ]
        csv << row
      end
      user
    end
  end

  def verify_by_omniauth(auth)
    account_link = case auth.provider
    when 'twitter'
      auth.info.urls.Twitter
    when 'linkedin'
      auth.info.urls.public_profile
    else
      "http://facebook.com/#{uid}"
    end

    verification = verifications.where(source: auth.provider, account: account_link, verified: true).first_or_initialize
    verification.update message: "#{auth.provider.titleize}"
  end


  def name
    "#{first_name} #{last_name}".presence || email.presence || "Unidentifier"
  end

  def name_with_initial
    first_name + " #{last_name[0]}."
  end

  def is_a_host?
    host.present?
  end

  def own_tour?(tour_id)
    tours.find(tour_id).present?
  end

  def verified?
    verifications.where(source: Verification::SOURCES, verified: true).size == Verification::SOURCES.size
  end

  def partial_verified?
    verifications.where(source: Verification::SOURCES, verified: true).size >= 2
  end

  Verification::SOURCES.each do |source|
    define_method "#{source}_verified?" do
      verifications.find_by(source: source).try(:verified)
    end
  end

  Verification::SOURCES.each do |source|
    define_method "#{source}_verification" do
      verifications.find_by(source: source)
    end
  end

  def total_reviews
    tours.inject(0){ |sum, tour| sum + tour.no_of_reviews }
  end

  def all_reviews
    TourReview.where(tour_id: tour_ids)
  end

  def total_references
    BookingReference.where(referral_code: self.invite_code).count
  end

  def current_bank_account
    bank_accounts.order('created_at ASC').first
  end

  def after_confirmation
    UserMailer.welcome_message(self).deliver_later!(wait: 5.seconds)
    super
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  ['facebook', 'twitter', 'linkedin'].each do |social|
    define_method "#{social}" do
      if is_only_verified?
        @user = User.from_omniauth(request.env["omniauth.auth"], current_user, is_only_verified?)
      else
        @user = User.from_omniauth(request.env["omniauth.auth"])
      end

      if @user.persisted?
        if is_only_verified?
          redirect_to send(referrer_path), notice: "You are verified via #{social.titleize}"
        else
          sign_in_and_redirect @user, :event => :authentication
          set_flash_message(:notice, :success, :kind => "#{social.titleize}") if is_navigational_format?
        end
      else
        if is_only_verified?
          redirect_to send(referrer_path), error: 'Cannot be verified via #{social.titleize}'
        else
          session["devise.#{social}_data"] = request.env["omniauth.auth"]
          flash[:alert] = "Cannot sign in with your #{social.titleize}"
          redirect_to new_user_registration_url
        end
      end
    end
  end

  private

  def extra_params
    request.env['omniauth.params']
  end

  def is_only_verified?
    extra_params['only_verified']
  end

  def referrer_path
    "#{extra_params['referrer_column'].presence || 'profile'}_users_path"
  end
end

app/controllers/users/references_controller.rb
class Users::ReferencesController < Devise::RegistrationsController
  before_action :authenticate_user!
  before_action :set_navigation

  def facebook
  end

  def twitter
  end

  def google_plus
  end

  def email
  end

  private

  def reference_params
    params.permit(:reference_email)
  end

  def set_navigation
    flash.now[:notice] = t('references.successfully')
    render 'referral.js'
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def update
    if current_user.update_attributes(password: user_params[:password], password_confirmation: user_params[:password_confirmation])
      sign_in(current_user, bypass: true)
      redirect_to users_path
      flash[:notice] = "Update password successfully"
    else
      redirect_to users_path
      flash[:error] = "New password is not acceptable"
    end
  end

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [:public_profile]
  before_action :fetch_reservations, only: [:reservations]
  before_action :fetch_travels, only: [:travels]
  before_action :fetch_crafted_tours, only: [:crafted_tours]
  before_action :get_public_user_tours, only: [:public_profile]
  before_action :set_bank_account, only: [:bank_accounts]
  before_action :set_location, only: [:update]
  before_action :set_column_navigation, only: [:reservations, :travels, :references, :verifications, :crafted_tours, :account_settings, :profile_information, :availability, :bank_accounts]

  def public_profile
    @reviews = TourReview.for_user(@user.id)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def crafted_tours; end
  def reservations; end
  def travels; end
  def verifications; end
  def account_settings; end
  def profile_information; end
  def availability; end
  def references; end
  def bank_accounts; end

  def index
    @column = 'profile'

    respond_to do |format|
      format.html
      format.js { render 'content.js' }
    end
  end

  def update
    @column = 'profile'
    flash.now[:notice] = "Update profile successfully" if current_user.update(@users_attributes)

    respond_to do |format|
      format.html { redirect_to users_path }
      format.js { render 'content.js' }
    end
  end

  def host
    @host = current_user.host || current_user.build_host
  end

  def twilio_send_message
    destroy_last_current_phone_number_verifications
    current_user.update(user_params)
    phone_verification = current_user.verifications.create(source: 'phone_number', account: user_params[:phone_number], verified: false, message: generate_token)
    twilio_number = ENV['TWILIO_NUMBER']
    @client = Twilio::REST::Client.new ENV['TWILIO_ACCOUNT_SID'], ENV['TWILIO_AUTH_TOKEN']
    message = @client.account.messages.create(
      :from => twilio_number,
      :to => user_params[:phone_number],
      :body => "Your verification code is #{@token}"
    )
    puts message.to

    respond_to do |format|
      format.js { render 'users/verifications/twilio.js'}
    end
  end

  def twilio_verify
    if current_user.phone_number_verification.message == params[:verification_code]
      current_user.phone_number_verification.verify!

      render json: {success: true}, status: :ok
    else
      render json: {success: false}, status: :ok
    end
  end

  private

  def generate_token
    @token = rand(0000..999999).to_s.rjust(4, "0")
  end

  def destroy_last_current_phone_number_verifications
    current_user.verifications.where(source: 'phone_number').destroy_all
  end

  def set_column_navigation
    @column = action_name
    respond_to do |format|
      format.html { render 'index.html' }
      format.js { render 'content.js' }
    end
  end

  def user_params
    params.require(:user).permit(:video_presentation, :gender, :phone_number, :phone, :job_title, :biography, :date_of_birth, :hobbies, :guide_type, :nationality_id, :primary_address_id, :primary_address, :email, :first_name, :last_name, :avatar, languages: [])
  end

  def fetch_reservations
    if params[:status] == 'confirmed'
      @reservations = current_user.reservations.completed
    else
      @reservations = current_user.reservations.pending
    end
    @reservations.includes(:tour)
  end

  def fetch_travels
    @reservations = current_user.reservations.completed
    @travels = @reservations.for_tours
  end

  def fetch_crafted_tours
    @tours = current_user.tours.page(params[:page]).per(6)
  end

  def get_public_user_tours
    @user = User.find(params[:id])
    # TODO: handle paginate properly
    @tours = @user.tours.page(params[:page]).per(10)
  end

  def set_bank_account
    @bank_account = current_user.current_bank_account || current_user.bank_accounts.new
  end

  def location_params
    user_params[:primary_address] && params[:locate_primary_address].present? ? eval(user_params.require(:primary_address)) : nil
  end

  def set_location
    @location = Location.first_or_create(location_params) if location_params
    @users_attributes = user_params.except(:primary_address).merge(primary_address: @location)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def display_verified_status(user, source)
    if user.send("#{source}_verified?")
      (source == :phone_number) ? user.phone.mask_all_except_last_numbers(2,'▒') : "Verified"
    else
      "Not Verified"
    end
  end

  def display_signed_up_time(user)
    "Member since #{user.created_at.strftime('%B %Y')}"
  end

end

app/views/users/_content_account_settings.html.haml
.row
  .small-12.columns
    = render 'profile_navbar'

#profile
  .row
    .small-12.medium-7.columns
      %h4.manage-header Change Password
      .change-password.space-top
        = simple_form_for(current_user, as: :user, url: user_registration_path(current_user), method: :put, html: { class: 'ng-pristine ng-valid' }) do |f|
          = f.input :email, id: 'traveler_email', required: true, input_html: { disabled: true }
          = f.input :password, autocomplete: 'off', label: 'New Password'
          = f.input :password_confirmation
          .text-right
            = f.button :submit, 'Update Password', 'data-disable-with' => 'Updating', class: 'button expand'

:javascript
  $(function(){
    $('.content-column').removeClass('free-meals');
    $('li.profile>a').addClass('current');
  });

app/views/users/_content_availability.html.haml
.row
  .small-12.columns
    = render 'profile_navbar'

#profile
  .row
    .small-12.medium-7.columns
      %h4.manage-header Availability
      .space-top

:javascript
  $(function(){
    $('.content-column').removeClass('free-meals');
    $('li.availability>a').addClass('current');
    $('li.profile>a').addClass('current');
  });

app/views/users/_content_pending_reservations.html.haml
.row
  .small-12.columns
    %ul.breadcrumbs
      %li
        = link_to "#{current_user.name}", users_path, remote: true
      %li.unavailable
        %a{:href => "#"} Pending Reservations
.row.overflow-scroll-x
  = render 'reservation_table', reservations: @reservations

:javascript
  $(function(){
    $('.content-column').removeClass('free-meals');
    $('li.pending-reservations>a').addClass('current');
  });

app/views/users/_content_profile.html.haml
.row
  .small-12.columns
    = render 'profile_navbar'

#profile
  = simple_form_for(current_user, url: user_path(current_user.id), method: :put, remote: true, html: { class: 'ng-pristine ng-valid' }) do |f|
    .row
      .small-12.medium-7.columns
        %h4.manage-header Profile
        = f.input :first_name, required: true
        = f.input :last_name, required: true
        = f.input :biography, as: :text, input_html: { rows: 10, type: 'text', placeholder: 'From 50 to 500 characters that describes yourself the best' }
        %label.label--with-hint{for: 'user_video_presentation'}
          Upload Video Presentation
        %a.label-hint.js--video-hint{href: '#'}
          Need suggestions?
          %i.fa.fa-info-circle
          %span.hidden (Close)
        #cover-upload-video-container.upload-container.preview
          %ul.preview-items-cover
          %div
            %span.icon.fa.fa-video-camera
            %p Click to upload.
            #temporary-video-presentation.text_center{style: 'word-wrap: break-word;'}= current_user.video_presentation.try(:url)
          %div.hidden.video-hint-block
            %h5 Suggestions for Personal Video Profile
            %p Intro/Name
            %p Where you are from?
            %p Where you live now and long you have lived there
            %p Your occupation and what you like to do for fun
            %p Why you joined TourMega
        = f.input :video_presentation, as: :file, input_html: { accept: "video/mp4, video/quicktime, video/x-m4v, video/ogg, video/avi, video/*", class: 'hidden' }, label: false
        .text-right
          = link_to 'View Your Profile', public_profile_user_path(current_user), target: '_blank', class: 'button btn btn-default'
          = f.button :submit, 'Update Profile', 'data-disable-with' => 'Updating', class: 'button'
      .small-12.medium-5.columns
        %h4.manage-header Profile Picture
        .row
          .small-12.medium-6.columns.user-info.text-center
            .vertical-align
              = f.input :avatar, as: :file, input_html: { accept: "image/png,image/gif,image/jpeg", class: 'hidden'}, label: 'Change Picture'
          .small-12.medium-6.columns.user-info.text-center
            .vertical-align
              = image_tag f.object.avatar_url, alt: f.object.name, class: 'avatar large'
          .small-12.text-center
            %a.js--profile-requirements{href: "#"} Personal Profile Requirements
          .small-12.columns.text-center.hidden
            %img{:src => "", id: 'temporary-avatar', width: '300px', height:'300px', style: 'margin-bottom: 20px;' }
            .form-group
              %label.string{style: 'padding-left: 60px;'} Click on the update button below to update your picture

:javascript
  $(function(){
    $('.vertical-align:has(img)').on('click', function(){
      $('#user_avatar').click();
    });

    $('#user_video_presentation').on('change', function(){
      readVideoURL(this, $('#temporary-video-presentation'));
    });

    $('#cover-upload-video-container').on('click', function(){
      $('#user_video_presentation').click();
    });

    function readURL(input) {
      if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
          $('#temporary-avatar').attr('src', e.target.result).attr('alt', 'Temporary Avatar').removeClass('hidden');
          $('#temporary-avatar').parent().removeClass('hidden');
        }
        reader.readAsDataURL(input.files[0]);
      }
    }

    $('#user_avatar').on('change', function(){
      readURL(this);
    });
    $('.content-column').removeClass('free-meals');
    $('li.profile>a').addClass('current');

    $(document).on('click', '.js--profile-requirements', function(){
      text = "<div class='modal-requirements'><p>Full Name of Company Account Manager must be included as part of your personal information (no company names)</p><p>Clear Profile Picture of Guide, no company logos</p><p>Minimum of 2 verifications but we recommend more</p><p>Indicate which methods you can be reached by travelers (e.g. WhatsApp, Skype, etc.)</p></div>"

      swal({   title: "Personal Profile Requirements",   text: text,   html: true });
    });

    $(document).on('click', '.js--video-hint', function(e){
      e.preventDefault();
      $('.js--video-hint span').toggleClass('hidden');
      $('.video-hint-block').toggleClass('hidden');
    });
  });

app/views/users/_content_profile_information.html.haml
.row
  .small-12.columns
    = render 'profile_navbar'

= javascript_include_tag 'gmap_autocomplete'

#profile
  = simple_form_for(current_user, url: user_path(current_user.id), method: :put, remote: true, html: { class: 'ng-pristine ng-valid' }) do |f|
    .row
      .small-12.medium-7.columns
        %h4.manage-header Personal
        = f.input :gender, as: :select, collection: User::GENDERS, required: true
        = f.input :phone_number, input_html: { placeholder: 'E.g. (+1) 322-454-3495' }
        = f.input :job_title, label: "Current occupation", input_html: { placeholder: 'Title' }
        = f.label 'Birthdate'
        = f.text_field :date_of_birth, class: 'form-control datepicker', placeholder: 'mm/dd/yyyy', label: 'Birth date'
        = f.input :hobbies, as: :text, input_html: { rows: 10, type: 'text', placeholder: 'From 50 to 250 characters that describes your hobbies the best' }
        .text-right
          = f.button :submit, 'Update Profile', 'data-disable-with' => 'Updating', class: 'button'
      .small-12.medium-5.columns
        %h4.manage-header Additional
        .row
          .small-12.columns.user-info
            = f.input :guide_type, as: :select, collection: User::GUIDE_TYPE.map{|e| [e.to_s.humanize, e]}
            = f.input :primary_address, as: :fake, input_html: { name: 'user[primary_address]', id: 'primary_address', class: 'hidden', value: f.object.primary_address.try(:hash_attributes) }, label: false, wrapper: false, required: false
            = f.input :locate_primary_address, as: :fake, input_html: { placeholder: 'Choose your current primary address', class: 'autocomplete-location', autocomplete: 'off', 'fill-to-input' => 'primary_address', value: f.object.primary_address.try(:address) }, label: 'Street Address (Unit/Apt #)'
            = f.input :languages, as: :select, collection: Tour::LANGUAGES, :input_html => { :class => "chosen-input with-bootstrap", multiple: true, 'data-placeholder' => "Choose a languages..." }, include_hidden: false, label: 'Languages'
            = f.input :nationality_id, as: :select, collection: Country.collection, :input_html => { :class => "chosen-input with-bootstrap", multiple: false }

:javascript
  loadGoogleMapScript('#{google_map_uri}', true, initAutocomplete);
  $(function(){
    $('.chosen-input').chosen({no_results_text: "No country match", placeholder_text_single: "Choose a country", allow_single_deselect: true, search_contains: true});
    $('.content-column').removeClass('free-meals');
    $('li.profile>a').addClass('current');
  });

app/views/users/_content_reservations.html.haml
.row
  .small-12.columns
    %ul.breadcrumbs
      %li.unavailable
        = link_to "Reservations", reservations_users_path, remote: true

.row.overflow-scroll-x
  = render 'reservation_table', reservations: @reservations

:javascript
  $(function(){
    $('.content-column').removeClass('free-meals');
    $('li.reservations>a').addClass('current');
  });

app/views/users/_panel_about_me.html.haml
.panel.panel-has-header.white-bg
  .panel-header About Me
  .panel-body
    %p= user.biography

app/views/users/_public_profile_tours.html.haml
.small-12.column
  .listings-container.flexslider
    %ul.slides
      - tours.each do |similar_tour|
        %li
          .item
            .panel-image.listing-img
              .media-photo
                %a{:href => "#{tour_path(similar_tour)}"}
                  %img{:src => "#{similar_tour.images.first.try(:url)}"}/

              %a.panel-overlay-bottom-left.panel-overlay-listing-price{:href => "#"}
                .price-container
                  %sup $
                  %span.price-amount= similar_tour.price
                %span.icon-instant-book.glyphicon.glyphicon-flash
            .panel-body.panel-card-section
              .info
                %a.profile-picture{:href => "#{public_profile_user_path(similar_tour.creator)}"}
                  %img{:alt => "name", :src => "#{similar_tour.creator_avatar_url}"}/
                %h3.listing-name{:title => "#{similar_tour.name}"}
                  %a{:href => "#{tour_path(similar_tour)}"}= similar_tour.name
                .listing-location
                  = render 'shared/tour_rating', tour: similar_tour

app/views/users/content.js.erb
$(function(){
  $('#profile_content').html("<%= j render('content_' + @column)%>");
  $('li>a').removeClass('current');
  $('.current-user-avatar').attr('src', "<%= current_user.avatar_url%>");
});

<%= render 'shared/flash_now_messages' %>

app/views/users/public_profile.html.haml
- content_for(:title, "#{@user.name} on TourMega")

.profile_public
  #wrapper
    #bg
    #main.row
      %header#header
        .row
          .small-12.medium-offset-1.medium-3.columns
            %img.avatar.current-user-avatar.avatar_public{:src => @user.avatar_url}
          .small-12.medium-5.columns
            %h1{style: "white-space: nowrap;"}= "#{@user.first_name} #{@user.last_name.first}."
            %a= [@user.try(:job_title), @user.try(:primary_address).try(:address)].compact.join(' • ')
            %nav
              %ul
                - Verification::SOCIAL_SOURCES.each do |src|
                  %li{style: "top:-120px;"}
                    - if @user.send("#{src}_verified?")
                      %a.icon.fa.fa-check{:href => "#"}
                    %a.icon-link.round.fill{:href => "#", class: "#{src}"}
                      %i.icon.fa{class: "fa-#{src}"}
                %li{style: "top:-120px;"}
                  %a.icon.fa.fa-check{:href => "#"}
                  %a.icon-link.round.fill{:href => "#", class: "envelope"}
                    %i.icon.fa{class: "fa-envelope"}
                %li{style: "top:-120px;"}
                  - if @user.send("phone_number_verified?")
                    %a.icon.fa.fa-check{:href => "#"}
                  %a.icon-link.round.fill{:href => "#", class: "phone"}
                    %i.icon.fa{class: "fa-phone"}
        .row
          .small-12
            - if @user.hobbies.present?
              %p= "I love #{@user.hobbies}"
            - if @user.biography.present?
              %p= @user.biography.html_safe
            - if @user.video_presentation?
              %p
                %video{:width => 320, :height => 240, :controls => true}
                  %source{:src => "#{@user.video_presentation.url}", :type => 'video/webm; codecs="vp8, vorbis"'}
                  %source{:src => "#{@user.video_presentation.url}", :type => 'video/mp4; codecs="vp8, vorbis"'}
                  %source{:src => "#{@user.video_presentation.url}", :type => 'video/ogg; codecs="vp8, vorbis"'}
    - if @tours.present?
      #user_tours.row
        #tours
          .row
            .small-12.medium-4.columns
              #tour_description
                %h1#tour_name= @tours.first.name
                %br
                %p.tour_description
                  = @tours.first.try(:description).try(:html_safe)
            .small-12.medium-8.columns
              .listings-container
                - @tours.each_slice(2) do |tours|
                  .row
                    - tours.each do |tour|
                      .small-6.medium-6.columns.image_column{data: {description: tour.try(:description).try(:html_safe), name: tour.name }}
                        .item
                          .panel-image.listing-img
                            .media-photo
                              .flexslider
                                %ul.slides
                                  - tour.images.each do |image|
                                    %li
                                      %a{:href => "#{tour_path(tour)}"}
                                        %img{:src => "#{image.url}"}/
                            %a.panel-overlay-bottom-left.panel-overlay-listing-price{:href => "#"}
                              .price-container
                                %sup $
                                %span.price-amount= tour.price.round
                              %span.icon-instant-book.glyphicon.glyphicon-flash


:javascript
  $(function(){
    $('body').removeClass().addClass('manage').attr('style','');
    $('#header').addClass('solid');

    $('.image_column').hover(function(){
      $('.tour_description').html($(this).data('description'));
      $('#tour_name').html($(this).data('name'));
    })

  });