config/routes.rb
Rails.application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'
  get 'errors/not_found'

  get 'errors/internal_server_error'

  root to: 'home#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks",
                                    :registrations => 'users/registrations' }
  begin
    ActiveAdmin.routes(self)
  rescue Exception => e
    puts "ActiveAdmin: #{e.class}: #{e}"
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  namespace :home, path: '/' do
    get :about
    get :become_guide
    get :partners
    get :term_of_services, path: 'term-of-services'
    get :privacy_policy, path: 'privacy-policy'
    get :copyright
    get :contact_us
    post :send_contact
    get :help
    get :example
    get :founders
    get :how_it_works, path: 'how-it-works'
    get :safety
    get :careers
    get :blog
  end

  resources :search, only: [:index, :create] do
  end

  resources :tours, path: 'tours' do
    member do
      get :profile
      put :update_profile, path: 'profile'
      patch :update_profile, path: 'profile'
      get :tour_itinerary
      put :update_tour_itinerary, path: 'tour_itinerary'
      get :additional_info
      put :update_additional_info, path: 'additional_info'
      get :preview
      put :update_preview, path: 'preview'
    end
    resources :reservations do
      member do
        get :passenger
        get :billing_information
        get :review_and_submit
      end
    end
  end

  resources :users, only: [:show, :update] do
    member do
      get :public_profile
    end
  end

  resources :users, only: [:index], path: '/manage/profile' do
    collection do
      get :host, path: 'guide'
      post 'become_guide' => 'hosts#create', :as => 'become_guide'
      get :references
      get :reservations
      get :travels
      get :crafted_tours
      get :verifications
      get :account_settings
      get :profile_information
      get :availability
      get :bank_accounts
      post :twilio_send_message
      post :twilio_verify
      resources :bank_accounts, only: [:create, :update]
    end
  end

  namespace :users, path: '/manage/profile' do
    devise_scope :user do
      resources :references, only: [] do
        collection do
          post :email
          post :facebook
          post :twitter
          post :google_plus
        end
      end
    end
  end

  resources :messages

  resources :countries do
    resources :cities, only: [:show]
  end

  resources :subscribers, only: [:create]
end

app/views/shared/_cover.html.haml
%section.cover.creator
  .clouds
  .clouds2
  .zeppelin
  .zeppelin2
  .airplane

app/views/shared/_cuisines.html.haml
.white-bg
  .row.wide
    .small-12.small-centered.medium-8.columns.text-center.guide.content.short
      %h3= t('cuisines.header')
      %p= t('cuisines.para')
.row.wide
  %ul.small-block-grid-1.medium-block-grid-2.large-block-grid-4.text-center.featured-food
    - cuisines.find_each do |cuisine|
      %li.space-bottom
        .row.collapse
          .small-12.columns.text-center
            = image_tag cuisine.image_url, alt: "#{cuisine.name} resizedForWeb"
            %h6= cuisine.name
            %p= cuisine.introduction

app/views/shared/_flash_messages.html.haml
- flash.each do |type, message|
  - if [:success, :alert, :notice, :error].include? type.to_sym
    %div.tourmega-notification.alert.alert-centered.auto-fade{ :class => twitterized_type(type) }
      %a.close{:href => "#", :"data-dismiss" => "alert"} ×
      %span
        = raw message

:javascript
  $(document).ready(function() {
    setTimeout(function() {
      $(".alert.auto-fade").fadeTo(500, 0).slideUp(500, function() {
        $(this).remove();
      });
    }, 3000);
  });

app/views/shared/_flash_now_messages.js.erb
$(function() {
  if ("<%= flash[:notice] || flash[:alert] || flash[:warning] %>") {
    if ("<%= flash[:notice] %>")
      (new FlashMessage({ type: "notice", message: "<%= flash[:notice] %>" })).show();
    else if ("<%= flash[:alert] %>")
      (new FlashMessage({ type: "error", message: "<%= flash[:error] %>" })).show();
    else
      (new FlashMessage({ type: "warning", message: "<%= flash[:warning] %>" })).show();
    setTimeout(function() {
      $(".alert.auto-fade").fadeTo(500, 0).slideUp(500, function() {
        $(this).remove();
      });
    }, 3000);
  }
});

app/views/shared/_map.html.haml
= javascript_include_tag 'gmap_tour_location'

.light-grey-bg
  .row
    .small-12.columns.text-center.space-top.space-bottom
      %h3= "Where we are #{in_country_of_city(place)}".html_safe
  .row.wide
    - if is_country?(place)
      .small-12.columns.text-center
        .host-cities
          We have tours in
          - place.cities.each_with_index do |city, index|
            = link_to city.name, country_city_path(place, city)
            = linking_word(index, @length ||= place.cities.length)
  .row.wide.collapse.map-container
    - if is_country?(place)
      #map-place-address.small-12.columns.picture{ style: 'width: 75%;', address: "#{place.name}", lat: "#{place.lat}", lng: "#{place.lng}", place: 'country' }
    - else
      #map-place-address.small-12.columns.picture{ style: 'width: 75%;', address: "#{place.geometry_name}", lat: "#{place.country.lat}", lng: "#{place.country.lng}" }
    .toolbox
      - if helper_toolbox_visible?
        .center
          .space-top.space-bottom
            = render 'resources/svg/airplane.html.haml'
          %h3 Let's travel
          %p Need help finding a local tour? Fill out our form and one of our travel specialists will get back to you!
          %a.button.wide{ href: "#{home_contact_us_path}" } ASK US A QUESTION

= include_gmap('initCountryOrCityMap', 'AIzaSyAVFzNOGekBgOKcvr31ekJPOS9I4dsioNc')

app/views/shared/_search_bar_with_city_and_country.html.haml
.row
  .small-6.columns.medium-12.locations-container.center
    %input#available_provinces.text-center{"aria-controls" => "locations", "aria-expanded" => "false", "data-dropdown" => "locations", :placeholder => "Where to go in #{country.name} ?", :readonly => "", :type => "text"}
      #locations.mega.f-dropdown.content{"data-dropdown-content" => "true"}
        .columns
          %ul
            - country.cities.each do |city|
              %li.province
                = link_to city.name, country_city_path(country, city)

app/views/shared/_search_form.html.haml
.small-9.columns.locations-container.center.text-center
  = simple_form_for(location, url: search_index_path, method: :get) do |f|
    .search-form-content
      .search-form-location
        = f.input :address, as: :fake, input_html: { placeholder: "#{t('input.placeholder.where_are_you_going')}", type: 'text', autocomplete: 'off', 'fill-to-input' => 'full_address', class: 'autocomplete-location', autofocus: autofocus }, wrapper: false, label: false
        = f.input :location, as: :fake, input_html: { name: 'location[full_address]', id: 'full_address', class: 'hidden' }, label: false, wrapper: false, required: true
      .search-form-date
        .date-start
          %input.checkin.datepicker{ type: 'text', placeholder: 'Start date', name: 'location[start_date]' }
    .search-form-action
      = f.button :submit, 'Search', class: 'button', style: 'margin: 0px 0px 5px 0px; height:42px; width: 100%;'

:javascript
  $(function(){
    $('.datepicker').datepicker({
      format: 'mm/dd/yyyy',
      todayHighlight: true,
      leftArrow: '&laquo;',
      rightArrow: '&raquo;',
      autoclose: true,
      orientation: "bottom"
    });
  });

app/views/shared/_spinner.html.haml
#spinner
  .sk-circle
    .sk-circle1.sk-child
    .sk-circle2.sk-child
    .sk-circle3.sk-child
    .sk-circle4.sk-child
    .sk-circle5.sk-child
    .sk-circle6.sk-child
    .sk-circle7.sk-child
    .sk-circle8.sk-child
    .sk-circle9.sk-child
    .sk-circle10.sk-child
    .sk-circle11.sk-child
    .sk-circle12.sk-child

:javascript
  $(function(){
    $('#spinner').hide();  // hide it initially.
    $(document)
      .ajaxStart(function() {
        $('#spinner').show(); // show on any Ajax event.
      })
      .ajaxStop(function() {
        $("#spinner").hide();
    });
  });

app/views/shared/_tour.html.haml
.item
  .panel-image.listing-img
    .media-photo
      .flexslider
        %ul.slides
          - tour.images.each do |image|
            %li
              %a{:href => "#{tour_path(tour)}"}
                %img{:src => "#{image.url}"}/
    %a.panel-overlay-bottom-left.panel-overlay-listing-price{:href => "#"}
      .price-container
        %sup $
        %span.price-amount= tour.price.round
      %span.icon-instant-book.glyphicon.glyphicon-flash
  .panel-body.panel-card-section
    .info
      %a.profile-picture{:href => "#{public_profile_user_path(tour.creator)}"}
        %img{:alt => "name", :src => "#{tour.creator_avatar_url}"}/
      %h3.listing-name{:title => "#{tour.name}"}
        %a{:href => "#{tour_path(tour)}"}= tour.name.try(:strip)
      .listing-location
        = render 'shared/tour_rating', tour: tour

app/views/shared/_tour_rating.html.haml
%a.text-normal
  = html_display_average_rating(tour)
  = display_reviews_count(tour)

app/views/shared/_tours.html.haml
- if tours.present?
  .listings-container
    .row
      - tours.each do |tour|
        .small-4.column
          = render 'shared/tour', tour: tour

  .footer-results{style: 'padding-left: 40px;'}
    = paginate tours, remote: true

app/views/shared/_zendesk.html.erb
<!-- Start of tourmega Zendesk Widget script -->
<script>/*<![CDATA[*/window.zEmbed||function(e,t){var n,o,d,i,s,a=[],r=document.createElement("iframe");window.zEmbed=function(){a.push(arguments)},window.zE=window.zE||window.zEmbed,r.src="javascript:false",r.title="",r.role="presentation",(r.frameElement||r).style.cssText="display: none",d=document.getElementsByTagName("script"),d=d[d.length-1],d.parentNode.insertBefore(r,d),i=r.contentWindow,s=i.document;try{o=s}catch(c){n=document.domain,r.src='javascript:var d=document.open();d.domain="'+n+'";void(0);',o=s}o.open()._l=function(){var o=this.createElement("script");n&&(this.domain=n),o.id="js-iframe-async",o.src=e,this.t=+new Date,this.zendeskHost=t,this.zEQueue=a,this.body.appendChild(o)},o.write('<body onload="document._l();">'),o.close()}("//assets.zendesk.com/embeddable_framework/main.js","tourmega.zendesk.com");
/*]]>*/</script>
<!-- End of tourmega Zendesk Widget script -->