config/routes.rb
Rails.application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'
  get 'errors/not_found'

  get 'errors/internal_server_error'

  root to: 'home#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks",
                                    :registrations => 'users/registrations' }
  begin
    ActiveAdmin.routes(self)
  rescue Exception => e
    puts "ActiveAdmin: #{e.class}: #{e}"
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  namespace :home, path: '/' do
    get :about
    get :become_guide
    get :partners
    get :term_of_services, path: 'term-of-services'
    get :privacy_policy, path: 'privacy-policy'
    get :copyright
    get :contact_us
    post :send_contact
    get :help
    get :example
    get :founders
    get :how_it_works, path: 'how-it-works'
    get :safety
    get :careers
    get :blog
  end

  resources :search, only: [:index, :create] do
  end

  resources :tours, path: 'tours' do
    member do
      get :profile
      put :update_profile, path: 'profile'
      patch :update_profile, path: 'profile'
      get :tour_itinerary
      put :update_tour_itinerary, path: 'tour_itinerary'
      get :additional_info
      put :update_additional_info, path: 'additional_info'
      get :preview
      put :update_preview, path: 'preview'
    end
    resources :reservations do
      member do
        get :passenger
        get :billing_information
        get :review_and_submit
      end
    end
  end

  resources :users, only: [:show, :update] do
    member do
      get :public_profile
    end
  end

  resources :users, only: [:index], path: '/manage/profile' do
    collection do
      get :host, path: 'guide'
      post 'become_guide' => 'hosts#create', :as => 'become_guide'
      get :references
      get :reservations
      get :travels
      get :crafted_tours
      get :verifications
      get :account_settings
      get :profile_information
      get :availability
      get :bank_accounts
      post :twilio_send_message
      post :twilio_verify
      resources :bank_accounts, only: [:create, :update]
    end
  end

  namespace :users, path: '/manage/profile' do
    devise_scope :user do
      resources :references, only: [] do
        collection do
          post :email
          post :facebook
          post :twitter
          post :google_plus
        end
      end
    end
  end

  resources :messages

  resources :countries do
    resources :cities, only: [:show]
  end

  resources :subscribers, only: [:create]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  LIMIT_SLIDE_NUMBER = 5

  before_action :prepare_data, only: [:index]
  before_action :set_column_navigation, only: [:about, :founders, :how_it_works, :careers]

  def example
    redirect_to root_path unless params[:example]
  end

  def index
    @featured_tours = Tour.joins(:categories).where.not(images: nil).order("RANDOM()").limit(4)
    # TODO: @Quynh: Please select the tours and update their featured = true
    # Then use this codes instead
    # @featured_tours = Tour.featured.limit(4)
  end

  def become_guide; end

  def founders
  end

  def about

  end

  def how_it_works
  end

  def partners
  end

  def safety

  end

  def careers

  end

  def help
  end

  def term_of_services; end

  def contact_us
    @contact = Contact.new
  end

  def privacy_policy; end
  def blog; end

  def send_contact
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to root_path, notice: "Your issue is on the right way"
    else
      redirect_to home_contact_us_path, alert: "There are missing things in your issue"
    end
  end

  protected

  def set_column_navigation
    @column = action_name
    respond_to do |format|
      format.html { render 'about.html' }
      format.js { render 'about.js' }
    end
  end

  def prepare_data
    @countries = Country.active_for_search
    @location = Location.new
    @slides = Slide.limit(LIMIT_SLIDE_NUMBER)
    @random_tour = Tour.featured.random
  end

  def contact_params
    params.require(:contact).permit(:name, :email, :subject, :content)
  end
end

app/views/home/_community.html.haml
.community-wrapper.container-fluid
  .space-8.text-center
    %h2 Our Service
  %ul.row.community-container.list-unstyled
    %li.col-md-3.col-sm-6
      .community-card.community-card-creating
        .panel
          %a.community-card-link.panel-image.media-photo.media-link.text-center{:href => "#{new_tour_path}"}
            .media-cover.media-cover-dark.background-cover
              %img{:src => "#{asset_url('service_backpack.jpg')}"}/
            .community-card-header
              .community-card-header-label
                %strong.text-contrast
                  Guide
            .row.row-table.row-full-height.text-contrast
              .col-sm-10.col-center.col-bottom
                .h3
                  %strong Make TourMega
                %div
                  Create your experiences,
                  %br/
                  Tell your story
    %li.col-md-3.col-sm-6
      .community-card.community-card-traveling
        .panel
          %a.community-card-link.panel-image.media-photo.media-link.text-center{:href => "#{countries_path}"}
            .media-cover.media-cover-dark.background-cover
              %img{:src => "#{asset_url('service_experience.jpg')}"}/
            .community-card-header
              .community-card-header-label
                %strong.text-contrast
                  Traveling
            .row.row-table.row-full-height.text-contrast
              .col-sm-10.col-center.col-bottom
                .h3
                  %strong Local travel
                %div
                  We are always searching for local experiences
    %li.col-md-3.col-sm-6
      .community-card.community-card-business
        .panel
          %a.community-card-link.panel-image.media-photo.media-link.text-center{:href => 'javascript:void(0);'}
            .media-cover.media-cover-dark.background-cover
              %img{:src => "#{asset_url('service_local.jpg')}"}/
            .community-card-header
              .community-card-header-label
                %strong.text-contrast
                  Day life
            .row.row-table.row-full-height.text-contrast
              .col-sm-11.col-center.col-bottom
                .h3
                  %strong Day life
                %div
                  Feel at home,
                  %br/
                  Enjoy local day-life services
    %li.col-md-3.col-sm-6
      .community-card.community-card-hosting
        .panel
          %a.community-card-link.panel-image.media-photo.media-link.text-center{:href => 'javascript:void(0);'}
            .media-cover.media-cover-dark.background-cover
              %img{:src => "#{asset_url('service_cuisine.jpg')}"}/
            .community-card-header
              .community-card-header-label
                %strong.text-contrast
                  Cuisine
            .row.row-table.row-full-height
              .col-sm-12.col-center.col-bottom.text-contrast
                .h3
                  %strong Authentic food
                %div
                  Experience the joy of a local meal,
                  %br/
                  In-home cooking

app/views/home/_destinations.html.haml
#destinations.white-bg
  .row.wide
    .small-12.columns.text-center
      %h2= t('home.intro_locations')
      .row.destinations{ data: { equalizer: '' } }
        - @countries.each do |country|
          %a.small-12.medium-6.large-3.columns.destination{href: "#{country_path(country)}"}
            .image.countries.lazy{style: "background-image: url(#{country.default_scene_image_url});"}
            .content
              %span= country.name
              %p

app/views/home/_featured_tours.html.haml
.community-wrapper.container-fluid
  .space-8.text-center
    %h2 Our Featured Tours
  %ul.row.community-container.list-unstyled
    - @featured_tours.each do |tour|
      %li.col-md-3.col-sm-6
        .community-card.community-card-creating
          .panel
            %a.community-card-link.panel-image.media-photo.media-link.text-center{:href => "#{tour_path(tour)}"}
              .media-cover.media-cover-dark.background-cover
                %img{:src => "#{tour.images.last.url}"}/
              .community-card-header
                .community-card-header-label
                  %strong.text-contrast
                    = tour.categories.first.name
              .row.row-table.row-full-height.text-contrast
                .col-sm-10.col-center.col-bottom
                  .h3
                    %strong
                      = tour.name

app/views/home/_press_coverage.html.haml
%section#press-coverage
  .row.medium-stacked
    .small-12.large-6.columns.text-center.left-column
      = link_to "javascript:void(0)" do
        %img{:alt => "#{t('home.press.main.alt')}", :src => "#{t('home.press.main.src')}"}
    .small-12.large-6.columns
      .row
        - t('home.press.sub.media').each do |index, media_url|
          .small-12.medium-4.columns.media-outlet{style: "background-image: url(#{media_url}); background-position: 50% 50%; background-repeat: no-repeat;"}
          = link_to '', "javascript:void(0)"

app/views/home/_tab_careers.html.haml
- content_for(:title, "Careers on TourMega")

:javascript
  $(function(){
    $('.careers-path>a').addClass('current');
  });

app/views/home/_tab_how_it_works.html.haml
- content_for(:title, "How TourMega works")

= javascript_include_tag 'gmap_autocomplete'

#desktop.border-bottom.white-bg.padding-bottom
  = render 'home/howitworks'
#safety-feedback.light-grey-bg
  .row.wide.small-stacked
    .small-12.medium-6.columns.content.text-center
      %h3
        %img{:alt => "backpack", :src => "#{asset_url('backpack.png')}"}
        %br
          Every guide is verified
      %p
        Safety and security are our top priorities.
    .small-12.medium-6.columns.content.text-center
      %h3
        %img{:alt => "feedback", :src => "#{asset_url('feedback.png')}"}
        %br
          Traveler feedback
      %p
        Hear from travelers about their TourMega experiences.
#browse-featured.white-bg
  .row
    .small-12.small-centered.columns.text-center.content
      %h3
        Start now
      = render 'shared/search_form', location: Location.new, autofocus: false


:javascript
  loadGoogleMapScript('#{google_map_uri}', true, initAutocomplete);
  $(function(){
    $('.how-it-works-path>a').addClass('current');
    $('#new_location input[type=submit]').css({'margin': '0', 'height': '36px'});
  });

app/views/home/_team_info_navigation.html.haml
.company-menu
  %h3 Team Info
  %nav
    %ul
      %li.about-path
        = link_to 'About', home_about_path, remote: true
      %li.founders-path
        = link_to 'Founders', home_founders_path, remote: true
      %li.how-it-works-path
        = link_to 'How it works', home_how_it_works_path, remote: true
      %li.safety-path.hidden
        = link_to 'Safety', home_safety_path, remote: true
      %li.careers-path.hidden
        = link_to 'Careers', home_careers_path, remote: true

app/views/home/_vet.html.haml
#vet.white-bg
  .row.small-stacked
    - %w(host safety ambassador).each do |content|
      .small-12.medium-4.columns.text-center
        %a{:href => "/become#{content}"}
          %svg.vet-icon
          %h3= t("home.vet.#{content}.header")
          %p= t("home.vet.#{content}.para")

app/views/home/about.html.haml
= javascript_include_tag 'history_state', media: 'all'

%section.main-section
  #about-page
    #hero{"background-image" => "https://d26oxw2p26xsun.cloudfront.net/assets/hero/about-c371bb10b02be473546f55b6d925abe2.jpg"}
      .message
        .row
          .small-12.small-centered.medium-10.large-8.columns.text-center
            %h1.larger Local guide
            %h1.larger for an authentic taste of life
    = render 'team_info_navigation'

    #information-tab
      = render "tab_#{@column}"

app/views/home/become_guide.html.haml
- content_for(:title, "Become our guide on TourMega")

%section.main-section
  #host-page
    #hero{ style: "background-image: url(#{t('become_guide.background_image')}); background-size: cover; background-position: 50% 25%; background-repeat: no-repeat;" }
      .message
        .row
          .small-12.small-centered.medium-10.large-8.columns.text-center
            %h1.larger= t('become_guide.header')
    #what-they-are.light-grey-bg
      .row.wide
        .small-12.large-8.large-centered.columns.content.text-center
          %h4= t('become_guide.introduction')
    #what-they-do.white-bg
      .row.wide{"data-equalizer" => ""}
        .small-12.medium-7.large-6.columns.content.shorter.large-stacked{"data-equalizer-watch" => "", :style => "height: 698px;"}
          .row
            .small-12.columns.space-top
              %h3.header= t('become_guide.application.header')
              %ul
                - t('become_guide.application.steps').each do |index, step|
                  %li
                    .step-circle.tiny= index + 1
                    = step
              %a.button.wide.space-top{:href => "#{host_users_path}"} Register a tour in 10 minutes
        .small-12.medium-5.large-6.columns.picture{ style: "height: 698px; background-image: url(#{t('become_guide.application.picture')}); background-size: cover; background-position: 50% 80%; background-repeat: no-repeat;" }
    #safety-feedback.light-grey-bg
      .row
        .small-12.small-centered.large-9.columns.content.text-center
          %h3.header
            Trust &amp; safety
          %p= t('become_guide.trust_and_safety')
    #host-faqs.photo-bg{ style: "background-image: url(#{t('become_guide.guide_photo_bg')}); background-size: cover; background-position: 50% 50%; background-repeat: no-repeat;" }
      .row
        .small-12.columns.content.text-center
          %h3{style: 'font-weight: 700;'} Your experience and creativity are the only limits

app/views/home/example.html.haml
%section.main-section{style: 'margin-top:300px;'}
  #host-selection-page
    #hero
      %img{:src => "/uploads/tour/images/2/IM.bin"}
      = render 'resources/svg/categories/art'
      = text_area_tag :editor, "", :class => "redactor", :rows => 40, :cols => 120

#map-popup-item
  .item
    .panel-image.listing-img
      .media-photo
        .flexslider
          %ul.slides
	          %li
	            %img{:src => "/uploads/tour/images/199/533f11a0-c234-4530-8217-1ec5f14d9c5f.jpg"}
	          %li
	            %img{:src => "/uploads/tour/images/199/e358f336-39aa-45b7-9af6-040ad221ff89.jpg"}
	          %li
	            %img{:src => "/uploads/tour/images/199/ef3c5bc4-2e26-4f70-ad6e-7b442d08d7b8.jpg"}
	          %li
	            %img{:src => "/uploads/tour/images/199/895950a6-1a3f-4333-a097-b5e5762c31fb.jpg"}
	          %li
	            %img{:src => "/uploads/tour/images/199/37107433-5232-494a-aedc-e40cbb2cd47f.jpg"}
      %a.panel-overlay-bottom-left.panel-overlay-listing-price{:href => "#"}
        .price-container
          %sup $
          %span.price-amount= 40.0
        %span.icon-instant-book.glyphicon.glyphicon-flash
    .panel-body.panel-card-section
      .info
        %a.profile-picture{:href => "#{}"}
          %img{:alt => "", :src => "/uploads/user/avatar/100/083593b5-9376-4de3-930e-00f1222ee6e1_small_1411087122_10341433_819249698103545_3004239799711702131_n.jpg"}/
        %h3.listing-name{:title => "Boat Trip / Paseo de Barco / Passeio de Barco"}
          %a{:href => "#"} = Boat Trip / Paseo de Barco / Passeio de Barco
        .listing-location
          %a.text-normal{:href => "#"}
            .star-rating
              %i.fa.fa-star
              %i.fa.fa-star
              %i.fa.fa-star
              %i.fa.fa-star
              %i.fa.fa-star-half-full
            = "5 reviews"

app/views/home/index.html.haml
%section#home.main-section
  - %w(slider destinations featured_tours).each do |content|
    = render "#{content}"

app/views/home/safety.html.haml
- content_for(:title, "Trust and Safety on TourMega")

%section.main-section
  #host-page
    #hero{"background-image" => "https://d26oxw2p26xsun.cloudfront.net/assets/hero/about-c371bb10b02be473546f55b6d925abe2.jpg"}
      .message
        .row
          .small-12.small-centered.medium-10.large-8.columns.text-center
            %h1.larger= "Trust and Safety"
    #what-they-are.light-grey-bg
      .row.wide
        .small-12.large-8.large-centered.columns.content.text-center
          %h4 TourMega is committed to providing a safe and secure environment for travelers and tour guides alike. As such, we have the following measures embedded in the platform to protect those using TourMega’s services.

    #safety-feedback.white-bg
      .row.wide.collapse
        .small-12.large-4.columns
          .row
            .small-12.medium-6.large-11.columns.content.short
              %h4.space-bottom
                %i.fa.fa-cc-stripe
                Secure Payments
              %p To ensure privacy and security when booking online, all transactions are encrypted and secure.  We do not store any of our customer's financial data on our platform. We utilize the secure Stripe platform which can process payments from anywhere in the world.

        .small-12.large-4.columns.middle-border
          .row
            .small-12.medium-6.large-11.columns.content.short
              %h4.space-bottom
                %i.fa.fa-certificate
                Verified Guides and Operators
              %p TourMega requires tour guides and operators submit to a verification process prior to posting on the platform. Verifications include the following: government ID, text, and social media verifications such as Linkedin, Facebook and Twitter. Each guide or operator must have at least two verifications in order to receive approval to post on TourMega.

        .small-12.large-4.columns
          .row
            .small-12.medium-6.large-11.columns.content.short
              %h4.space-bottom
                %i.fa.fa-comments
                Peer Reviews
              %p Peer reviews are an important tool that allow travelers to provide an honest assessment of the tour guides and experiences. After each tour or activity, travelers are given the option to rank their experience and provide both public and private feedback. Both types of feedback are used to ensure the experiences meet the high standards TourMega expects and will be used to determine which tours and activities are allowed on the platform.

    #host-faqs.photo-bg{ style: "background-image: url(#{t('become_guide.guide_photo_bg')}); background-size: cover; background-position: 50% 50%; background-repeat: no-repeat;" }
      .row
        .small-12.columns.content.text-center
          %h3{style: 'font-weight: 700;'} Your experience and creativity are the only limits